name: Build on Linux (Ubuntu)
on:
  push:
    branches:
      - main
  pull_request:

# linux does downloading and extraction fast, skip cache configuration

jobs:
  build-ubuntu:
    name: Linux (Ubuntu) build
    runs-on: ubuntu-latest

    env:
      VISIONR_VERSION: 11.0.0-alpha2

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install VisionR-Engine Globally (Linux)
        if: steps.cache-visionr.outputs.cache-hit != 'true'
        run: |
          echo "Installing VisionR-Engine globally..."
          npm install -g https://github.com/plan-vision/visionr-engine.binary/releases/download/${{ env.VISIONR_VERSION }}/visionr-engine-NPM-package-${{ env.VISIONR_VERSION }}.tar.gz

      - name: Compiling the project (Linux)
        run: vrs compile
        shell: bash
